name: sBanSystem
author: Sal4iDev
main: com.sal4i.sbansystem.SBanSystem
version: $version
description: Temporary ban system and other things to make your stuff easier
api-version: 1.20

commands:
  isban:
    aliases: [ checkban ]
    usage: /<command> [<player>]
    permission: sbansystem.isban
  tempban:
    usage: /<command> [<player>] [<amount><y;M;w;d;h;m;s>] (<reason>)
    permission: sbansystem.tempban